# Generated by Django 4.2.1 on 2023-06-21 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('idseccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('idropa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=2)),
                ('file', models.ImageField(upload_to='img/')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seccion')),
            ],
        ),
    ]
