# Generated by Django 4.2.1 on 2023-06-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ropa_rest.comuna')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ropa_rest.genero')),
            ],
        ),
    ]
